package org.cuatrovientos.signum.app;

import android.app.Application;
import android.graphics.drawable.Drawable;

import org.cuatrovientos.signum.Models.Categoria;
import org.cuatrovientos.signum.Models.Signo;
import org.cuatrovientos.signum.R;

import java.util.concurrent.atomic.AtomicInteger;

import io.realm.Realm;
import io.realm.RealmConfiguration;
import io.realm.RealmObject;
import io.realm.RealmResults;

public class MyAplication extends Application {

    public static AtomicInteger signosId = new AtomicInteger();
    public static AtomicInteger categoriasId = new AtomicInteger();

    @Override
    public void onCreate() {
        super.onCreate();

        setUpRealmConfig();
        Realm realm = Realm.getDefaultInstance();
        signosId = getIdByTable(realm, Signo.class);
        categoriasId = getIdByTable(realm, Categoria.class);
        realm.close();
    }

    private void setUpRealmConfig(){
        Realm.init(getApplicationContext());
        RealmConfiguration config = new RealmConfiguration
                .Builder()
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(config);
    }

    private <T extends RealmObject> AtomicInteger getIdByTable(Realm realm, Class<T> anyClass){

        RealmResults<T> results = realm.where(anyClass).findAll();

        if (results.size()>0){
            return new AtomicInteger(results.max("id").intValue());
        }else{
            realm.beginTransaction();
            Categoria ciudad = new Categoria("Ciudad", R.drawable.ciudad_categoria);
            realm.copyToRealm(ciudad);
            Categoria adjetivosAdverbiosVerbos = new Categoria("Adjetivos, Advervios y Verbos", R.drawable.ciudad_categoria);
            realm.copyToRealm(adjetivosAdverbiosVerbos);
            Categoria calendario = new Categoria("Calendario", R.drawable.ciudad_categoria);
            realm.copyToRealm(calendario);
            Categoria casa = new Categoria("Casa", R.drawable.ciudad_categoria);
            realm.copyToRealm(casa);
            Categoria colegio = new Categoria("Colegio", R.drawable.ciudad_categoria);
            realm.copyToRealm(colegio);
            Categoria comidasYBebidas = new Categoria("Calendario", R.drawable.ciudad_categoria);
            realm.copyToRealm(comidasYBebidas);
            Categoria cuerpo = new Categoria("Cuerpo", R.drawable.ciudad_categoria);
            realm.copyToRealm(cuerpo);
            Categoria familia = new Categoria("Familia", R.drawable.ciudad_categoria);
            realm.copyToRealm(familia);
            Categoria naturaleza = new Categoria("Naturaleza", R.drawable.ciudad_categoria);
            realm.copyToRealm(naturaleza);
            Categoria ropa = new Categoria("Ropa", R.drawable.ciudad_categoria);
            realm.copyToRealm(ropa);
            Categoria saludosPreguntas = new Categoria("Saludos y Preguntas", R.drawable.ciudad_categoria);
            realm.copyToRealm(saludosPreguntas);

            Signo ciudad1 = new Signo("Acera", R.drawable.ciudad_acera, ciudad.getId());
            realm.copyToRealm(ciudad1);
            Signo ciudad2 = new Signo("Ambulancia", R.drawable.ciudad_ambulancia, ciudad.getId());
            realm.copyToRealm(ciudad2);
            Signo ciudad3 = new Signo("Autobus", R.drawable.ciudad_autobus, ciudad.getId());
            realm.copyToRealm(ciudad3);
            Signo ciudad4 = new Signo("Biblioteca", R.drawable.ciudad_biblioteca, ciudad.getId());
            realm.copyToRealm(ciudad4);
            Signo ciudad5 = new Signo("Banco Dinero", R.drawable.ciudad_banco_dinero, ciudad.getId());
            realm.copyToRealm(ciudad5);
            Signo ciudad6 = new Signo("Banco Sentar", R.drawable.ciudad_banco_sentar, ciudad.getId());
            realm.copyToRealm(ciudad6);
            Signo ciudad7 = new Signo("Bicicleta", R.drawable.ciudad_bicicleta, ciudad.getId());
            realm.copyToRealm(ciudad7);
            Signo ciudad8 = new Signo("Bombero", R.drawable.ciudad_bombero, ciudad.getId());
            realm.copyToRealm(ciudad8);
            Signo ciudad9 = new Signo("Buzon", R.drawable.ciudad_buzon, ciudad.getId());
            realm.copyToRealm(ciudad9);
            Signo ciudad10 = new Signo("Calle", R.drawable.ciudad_calle, ciudad.getId());
            realm.copyToRealm(ciudad10);
            Signo ciudad11 = new Signo("Camion", R.drawable.ciudad_camion, ciudad.getId());
            realm.copyToRealm(ciudad11);
            Signo ciudad12 = new Signo("Cine", R.drawable.ciudad_cine, ciudad.getId());
            realm.copyToRealm(ciudad12);
            Signo ciudad13 = new Signo("Acera", R.drawable.ciudad_ciudad, ciudad.getId());
            realm.copyToRealm(ciudad13);
            Signo ciudad14 = new Signo("Ciudad Barca", R.drawable.ciudad_ciudad_barca, ciudad.getId());
            realm.copyToRealm(ciudad14);
            Signo ciudad15 = new Signo("Coche", R.drawable.ciudad_coche, ciudad.getId());
            realm.copyToRealm(ciudad15);
            Signo ciudad16 = new Signo("Colegio", R.drawable.ciudad_colegio, ciudad.getId());
            realm.copyToRealm(ciudad16);
            Signo ciudad17 = new Signo("Columpio", R.drawable.ciudad_columpio, ciudad.getId());
            realm.copyToRealm(ciudad17);
            Signo ciudad18 = new Signo("Farola", R.drawable.ciudad_farola, ciudad.getId());
            realm.copyToRealm(ciudad18);
            Signo ciudad19 = new Signo("Fuente", R.drawable.ciudad_fuente, ciudad.getId());
            realm.copyToRealm(ciudad19);
            Signo ciudad20 = new Signo("Hospital", R.drawable.ciudad_hospital, ciudad.getId());
            realm.copyToRealm(ciudad20);
            Signo ciudad21 = new Signo("Libreria", R.drawable.ciudad_libreria, ciudad.getId());
            realm.copyToRealm(ciudad21);
            Signo ciudad22 = new Signo("Luz", R.drawable.ciudad_luz, ciudad.getId());
            realm.copyToRealm(ciudad22);
            Signo ciudad23 = new Signo("Medico", R.drawable.ciudad_medico, ciudad.getId());
            realm.copyToRealm(ciudad23);
            Signo ciudad24 = new Signo("Moto", R.drawable.ciudad_moto, ciudad.getId());
            realm.copyToRealm(ciudad24);
            Signo ciudad25 = new Signo("Moto", R.drawable.ciudad_museo, ciudad.getId());
            realm.copyToRealm(ciudad25);
            Signo ciudad26 = new Signo("Paso de Cebra", R.drawable.ciudad_paso_de_cebra, ciudad.getId());
            realm.copyToRealm(ciudad26);
            Signo ciudad27 = new Signo("Pasteleria", R.drawable.ciudad_pasteleria, ciudad.getId());
            realm.copyToRealm(ciudad27);
            Signo ciudad28 = new Signo("Pastelero", R.drawable.ciudad_pastelero, ciudad.getId());
            realm.copyToRealm(ciudad28);
            Signo ciudad29 = new Signo("Pescador", R.drawable.ciudad_pescador, ciudad.getId());
            realm.copyToRealm(ciudad29);
            Signo ciudad30 = new Signo("Plaza", R.drawable.ciudad_plaza, ciudad.getId());
            realm.copyToRealm(ciudad30);
            Signo ciudad31 = new Signo("Policia", R.drawable.ciudad_policia, ciudad.getId());
            realm.copyToRealm(ciudad31);
            Signo ciudad32 = new Signo("Profesiones", R.drawable.ciudad_profesiones, ciudad.getId());
            realm.copyToRealm(ciudad32);
            Signo ciudad33 = new Signo("Profesor", R.drawable.ciudad_profesor, ciudad.getId());
            realm.copyToRealm(ciudad33);
            Signo ciudad34 = new Signo("Puente", R.drawable.ciudad_puente, ciudad.getId());
            realm.copyToRealm(ciudad34);
            Signo ciudad35 = new Signo("Quiosco", R.drawable.ciudad_quiosco, ciudad.getId());
            realm.copyToRealm(ciudad35);
            Signo ciudad36 = new Signo("Semaforo", R.drawable.ciudad_semaforo, ciudad.getId());
            realm.copyToRealm(ciudad36);
            Signo ciudad37 = new Signo("Supermercado", R.drawable.ciudad_supermercado, ciudad.getId());
            realm.copyToRealm(ciudad37);
            Signo ciudad38 = new Signo("Teatro", R.drawable.ciudad_teatro, ciudad.getId());
            realm.copyToRealm(ciudad38);
            Signo ciudad39 = new Signo("Tienda", R.drawable.ciudad_tienda, ciudad.getId());
            realm.copyToRealm(ciudad39);
            Signo ciudad40 = new Signo("Tobogan", R.drawable.ciudad_tobogan, ciudad.getId());
            realm.copyToRealm(ciudad40);
            Signo ciudad41 = new Signo("Transporte", R.drawable.ciudad_transporte, ciudad.getId());
            realm.copyToRealm(ciudad41);
            Signo ciudad42 = new Signo("Vehiculo", R.drawable.ciudad_vehiculo, ciudad.getId());
            realm.copyToRealm(ciudad42);
            Signo ciudad43 = new Signo("Zapateria", R.drawable.ciudad_zapateria, ciudad.getId());
            realm.copyToRealm(ciudad43);
            Signo ciudad44 = new Signo("Ciudad", R.drawable.ciudad_ciudad, ciudad.getId());
            realm.copyToRealm(ciudad44);

            Signo adjetivosAdverbiosVerbos1 = new Signo("abajo", R.drawable.aaverbos_abajo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos1);
            Signo adjetivosAdverbiosVerbos2 = new Signo("abrazar", R.drawable.aaverbos_abrazar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos2);
            Signo adjetivosAdverbiosVerbos3 = new Signo("aburrido", R.drawable.aaverbos_aburrido, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos3);
            Signo adjetivosAdverbiosVerbos4 = new Signo("acido", R.drawable.aaverbos_acido, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos4);
            Signo adjetivosAdverbiosVerbos5 = new Signo("adjetivos", R.drawable.aaverbos_adjetivos, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos5);
            Signo adjetivosAdverbiosVerbos6 = new Signo("adverbio", R.drawable.aaverbos_adverbio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos6);
            Signo adjetivosAdverbiosVerbos7 = new Signo("agradable", R.drawable.aaverbos_agradable, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos7);
            Signo adjetivosAdverbiosVerbos8 = new Signo("alegre", R.drawable.aaverbos_alegre, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos8);
            Signo adjetivosAdverbiosVerbos9 = new Signo("alto", R.drawable.aaverbos_alto, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos9);
            Signo adjetivosAdverbiosVerbos10 = new Signo("amar", R.drawable.aaverbos_amar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos10);
            Signo adjetivosAdverbiosVerbos11 = new Signo("amargo", R.drawable.aaverbos_amargo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos11);
            Signo adjetivosAdverbiosVerbos12 = new Signo("andar", R.drawable.aaverbos_andar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos12);
            Signo adjetivosAdverbiosVerbos13 = new Signo("aprender", R.drawable.aaverbos_aprender, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos13);
            Signo adjetivosAdverbiosVerbos14 = new Signo("arriba", R.drawable.aaverbos_arriba, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos14);
            Signo adjetivosAdverbiosVerbos15 = new Signo("ayudar", R.drawable.aaverbos_ayudar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos15);
            Signo adjetivosAdverbiosVerbos16 = new Signo("bajo", R.drawable.aaverbos_bajo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos16);
            Signo adjetivosAdverbiosVerbos17 = new Signo("beber", R.drawable.aaverbos_beber, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos17);
            Signo adjetivosAdverbiosVerbos18 = new Signo("besar", R.drawable.aaverbos_besar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos18);
            Signo adjetivosAdverbiosVerbos19 = new Signo("bien", R.drawable.aaverbos_bien, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos19);
            Signo adjetivosAdverbiosVerbos20 = new Signo("blando", R.drawable.aaverbos_blando, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos20);
            Signo adjetivosAdverbiosVerbos21 = new Signo("bueno", R.drawable.aaverbos_bueno, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos21);
            Signo adjetivosAdverbiosVerbos22 = new Signo("caliente", R.drawable.aaverbos_caliente, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos22);
            Signo adjetivosAdverbiosVerbos23 = new Signo("castano", R.drawable.aaverbos_castano, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos23);
            Signo adjetivosAdverbiosVerbos24 = new Signo("cerca", R.drawable.aaverbos_cerca, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos24);
            Signo adjetivosAdverbiosVerbos25 = new Signo("claro", R.drawable.aaverbos_claro, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos25);
            Signo adjetivosAdverbiosVerbos26 = new Signo("comer", R.drawable.aaverbos_comer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos26);
            Signo adjetivosAdverbiosVerbos27 = new Signo("comprar", R.drawable.aaverbos_comprar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos27);
            Signo adjetivosAdverbiosVerbos28 = new Signo("conocer", R.drawable.aaverbos_conocer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos28);
            Signo adjetivosAdverbiosVerbos29 = new Signo("contar", R.drawable.aaverbos_contar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos29);
            Signo adjetivosAdverbiosVerbos30 = new Signo("contento", R.drawable.aaverbos_contento, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos30);
            Signo adjetivosAdverbiosVerbos31 = new Signo("correr", R.drawable.aaverbos_correr, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos31);
            Signo adjetivosAdverbiosVerbos32 = new Signo("cortar", R.drawable.aaverbos_cortar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos32);
            Signo adjetivosAdverbiosVerbos33 = new Signo("crecer-planta", R.drawable.aaverbos_crecer_planta, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos33);
            Signo adjetivosAdverbiosVerbos34 = new Signo("crecer", R.drawable.aaverbos_crecer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos34);
            Signo adjetivosAdverbiosVerbos35 = new Signo("debajo", R.drawable.aaverbos_debajo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos35);
            Signo adjetivosAdverbiosVerbos36 = new Signo("delante", R.drawable.aaverbos_delante, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos36);
            Signo adjetivosAdverbiosVerbos37 = new Signo("delgado", R.drawable.aaverbos_delgado, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos37);
            Signo adjetivosAdverbiosVerbos38 = new Signo("dentro", R.drawable.aaverbos_dentro, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos38);
            Signo adjetivosAdverbiosVerbos39 = new Signo("derecha", R.drawable.aaverbos_derecha, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos39);
            Signo adjetivosAdverbiosVerbos40 = new Signo("desagradable", R.drawable.aaverbos_desagradable, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos40);
            Signo adjetivosAdverbiosVerbos41 = new Signo("descansar", R.drawable.aaverbos_descansar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos41);
            Signo adjetivosAdverbiosVerbos42 = new Signo("detras", R.drawable.aaverbos_detras, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos42);
            Signo adjetivosAdverbiosVerbos43 = new Signo("diferente", R.drawable.aaverbos_diferente, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos43);
            Signo adjetivosAdverbiosVerbos44 = new Signo("divertido", R.drawable.aaverbos_divertido, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos44);
            Signo adjetivosAdverbiosVerbos45 = new Signo("dormir", R.drawable.aaverbos_dormir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos45);
            Signo adjetivosAdverbiosVerbos46 = new Signo("ducharse", R.drawable.aaverbos_ducharse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos46);
            Signo adjetivosAdverbiosVerbos47 = new Signo("dulce (1)", R.drawable.aaverbos_dulce__1_, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos47);
            Signo adjetivosAdverbiosVerbos48 = new Signo("dulce", R.drawable.aaverbos_dulce, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos48);
            Signo adjetivosAdverbiosVerbos49 = new Signo("duro", R.drawable.aaverbos_duro, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos49);
            Signo adjetivosAdverbiosVerbos50 = new Signo("encima", R.drawable.aaverbos_encima, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos50);
            Signo adjetivosAdverbiosVerbos51 = new Signo("enfadado", R.drawable.aaverbos_enfadado, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos51);
            Signo adjetivosAdverbiosVerbos52 = new Signo("enfermo", R.drawable.aaverbos_enfermo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos52);
            Signo adjetivosAdverbiosVerbos53 = new Signo("entender", R.drawable.aaverbos_entender, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos53);
            Signo adjetivosAdverbiosVerbos54 = new Signo("escribir", R.drawable.aaverbos_escribir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos54);
            Signo adjetivosAdverbiosVerbos55 = new Signo("esperar", R.drawable.aaverbos_esperar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos55);
            Signo adjetivosAdverbiosVerbos56 = new Signo("explicar", R.drawable.aaverbos_explicar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos56);
            Signo adjetivosAdverbiosVerbos57 = new Signo("feo", R.drawable.aaverbos_feo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos57);
            Signo adjetivosAdverbiosVerbos58 = new Signo("frio", R.drawable.aaverbos_frio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos58);
            Signo adjetivosAdverbiosVerbos59 = new Signo("fuera", R.drawable.aaverbos_fuera, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos59);
            Signo adjetivosAdverbiosVerbos60 = new Signo("gordo", R.drawable.aaverbos_gordo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos60);
            Signo adjetivosAdverbiosVerbos61 = new Signo("gritar", R.drawable.aaverbos_gritar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos61);
            Signo adjetivosAdverbiosVerbos62 = new Signo("guapo", R.drawable.aaverbos_guapo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos62);
            Signo adjetivosAdverbiosVerbos63 = new Signo("gustar", R.drawable.aaverbos_gustar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos63);
            Signo adjetivosAdverbiosVerbos64 = new Signo("hablar-lse", R.drawable.aaverbos_hablar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos64);
            Signo adjetivosAdverbiosVerbos65 = new Signo("hablar-oral", R.drawable.aaverbos_hablar_oral, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos65);
            Signo adjetivosAdverbiosVerbos66 = new Signo("igual", R.drawable.aaverbos_igual, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos66);
            Signo adjetivosAdverbiosVerbos67 = new Signo("izquierda", R.drawable.aaverbos_izquierda, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos67);
            Signo adjetivosAdverbiosVerbos68 = new Signo("jugar", R.drawable.aaverbos_jugar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos68);
            Signo adjetivosAdverbiosVerbos69 = new Signo("lavar-la-cabeza", R.drawable.aaverbos_lavar_la_cabeza, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos69);
            Signo adjetivosAdverbiosVerbos70 = new Signo("lavar-la-ropa", R.drawable.aaverbos_lavar_la_ropa, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos70);
            Signo adjetivosAdverbiosVerbos71 = new Signo("lavar-los-dientes", R.drawable.aaverbos_lavar_los_dientes, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos71);
            Signo adjetivosAdverbiosVerbos72 = new Signo("leer", R.drawable.aaverbos_leer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos72);
            Signo adjetivosAdverbiosVerbos73 = new Signo("lejos", R.drawable.aaverbos_lejos, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos73);
            Signo adjetivosAdverbiosVerbos74 = new Signo("lento", R.drawable.aaverbos_lento, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos74);
            Signo adjetivosAdverbiosVerbos75 = new Signo("levantarse", R.drawable.aaverbos_levantarse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos75);
            Signo adjetivosAdverbiosVerbos76 = new Signo("limpio", R.drawable.aaverbos_limpio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos76);
            Signo adjetivosAdverbiosVerbos77 = new Signo("lleno", R.drawable.aaverbos_lleno, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos77);
            Signo adjetivosAdverbiosVerbos78 = new Signo("llorar", R.drawable.aaverbos_llorar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos78);
            Signo adjetivosAdverbiosVerbos79 = new Signo("mal", R.drawable.aaverbos_mal, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos79);
            Signo adjetivosAdverbiosVerbos80 = new Signo("malo", R.drawable.aaverbos_malo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos80);
            Signo adjetivosAdverbiosVerbos81 = new Signo("montar", R.drawable.aaverbos_montar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos81);
            Signo adjetivosAdverbiosVerbos82 = new Signo("moreno", R.drawable.aaverbos_moreno, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos82);
            Signo adjetivosAdverbiosVerbos83 = new Signo("mucho", R.drawable.aaverbos_mucho, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos83);
            Signo adjetivosAdverbiosVerbos84 = new Signo("nacer", R.drawable.aaverbos_nacer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos84);
            Signo adjetivosAdverbiosVerbos85 = new Signo("no-conocer", R.drawable.aaverbos_no_conocer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos85);
            Signo adjetivosAdverbiosVerbos86 = new Signo("no-gustar", R.drawable.aaverbos_no_gustar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos86);
            Signo adjetivosAdverbiosVerbos87 = new Signo("no-tener", R.drawable.aaverbos_no_tener, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos87);
            Signo adjetivosAdverbiosVerbos88 = new Signo("oir", R.drawable.aaverbos_oir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos88);
            Signo adjetivosAdverbiosVerbos89 = new Signo("oler", R.drawable.aaverbos_oler, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos89);
            Signo adjetivosAdverbiosVerbos90 = new Signo("oscuro", R.drawable.aaverbos_oscuro, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos90);
            Signo adjetivosAdverbiosVerbos91 = new Signo("pasear", R.drawable.aaverbos_pasear, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos91);
            Signo adjetivosAdverbiosVerbos92 = new Signo("patinar", R.drawable.aaverbos_patinar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos92);
            Signo adjetivosAdverbiosVerbos93 = new Signo("pegar", R.drawable.aaverbos_pegar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos93);
            Signo adjetivosAdverbiosVerbos94 = new Signo("peinarse", R.drawable.aaverbos_peinarse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos94);
            Signo adjetivosAdverbiosVerbos95 = new Signo("pelirrojo", R.drawable.aaverbos_pelirrojo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos95);
            Signo adjetivosAdverbiosVerbos96 = new Signo("poco", R.drawable.aaverbos_aaverbos_poco, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos96);
            Signo adjetivosAdverbiosVerbos97 = new Signo("ponerse", R.drawable.aaverbos_ponerse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos97);
            Signo adjetivosAdverbiosVerbos98 = new Signo("primer", R.drawable.aaverbos_primer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos98);
            Signo adjetivosAdverbiosVerbos99 = new Signo("quitarse", R.drawable.aaverbos_quitarse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos99);
            Signo adjetivosAdverbiosVerbos100 = new Signo("rapido", R.drawable.aaverbos_rapido, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos100);
            Signo adjetivosAdverbiosVerbos101 = new Signo("regalar", R.drawable.aaverbos_regalar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos101);
            Signo adjetivosAdverbiosVerbos102 = new Signo("reir", R.drawable.aaverbos_reir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos102);
            Signo adjetivosAdverbiosVerbos103 = new Signo("rubio", R.drawable.aaverbos_rubio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos103);
            Signo adjetivosAdverbiosVerbos104 = new Signo("saborear", R.drawable.aaverbos_saborear, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos104);
            Signo adjetivosAdverbiosVerbos105 = new Signo("salado", R.drawable.aaverbos_salado, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos105);
            Signo adjetivosAdverbiosVerbos106 = new Signo("saltar", R.drawable.aaverbos_saltar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos106);
            Signo adjetivosAdverbiosVerbos107 = new Signo("sano", R.drawable.aaverbos_sano, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos107);
            Signo adjetivosAdverbiosVerbos108 = new Signo("sentarse", R.drawable.aaverbos_sentarse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos108);
            Signo adjetivosAdverbiosVerbos109 = new Signo("sucio", R.drawable.aaverbos_sucio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos109);
            Signo adjetivosAdverbiosVerbos110 = new Signo("templado", R.drawable.aaverbos_templado, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos110);
            Signo adjetivosAdverbiosVerbos111 = new Signo("tener", R.drawable.aaverbos_tener, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos111);
            Signo adjetivosAdverbiosVerbos112 = new Signo("tocar", R.drawable.aaverbos_tocar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos112);
            Signo adjetivosAdverbiosVerbos113 = new Signo("triste", R.drawable.aaverbos_triste, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos113);
            Signo adjetivosAdverbiosVerbos114 = new Signo("ultimo", R.drawable.aaverbos_ultimo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos114);
            Signo adjetivosAdverbiosVerbos115 = new Signo("vacio", R.drawable.aaverbos_vacio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos115);
            Signo adjetivosAdverbiosVerbos116 = new Signo("vamos-a", R.drawable.aaverbos_vamos_a, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos116);
            Signo adjetivosAdverbiosVerbos117 = new Signo("ver", R.drawable.aaverbos_ver, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos117);
            Signo adjetivosAdverbiosVerbos118 = new Signo("verbo", R.drawable.aaverbos_verbo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos118);
            Signo adjetivosAdverbiosVerbos119 = new Signo("vestirse", R.drawable.aaverbos_vestirse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos119);
            Signo adjetivosAdverbiosVerbos120 = new Signo("vivir", R.drawable.aaverbos_vivir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos120);

            Signo calendario1 = new Signo("ayer", R.drawable.calendario_ayer, calendario.getId());
            realm.copyToRealm(calendario1);
            Signo calendario2 = new Signo("calendario", R.drawable.calendario_calendario, calendario.getId());
            realm.copyToRealm(calendario2);
            Signo calendario3 = new Signo("cumpleanos", R.drawable.calendario_cumpleanos, calendario.getId());
            realm.copyToRealm(calendario3);
            Signo calendario4 = new Signo("dia-de-la-semana", R.drawable.calendario_dia_de_la_semana, calendario.getId());
            realm.copyToRealm(calendario4);
            Signo calendario5 = new Signo("dia-manana", R.drawable.calendario_dia_manana, calendario.getId());
            realm.copyToRealm(calendario5);
            Signo calendario6 = new Signo("diciembre", R.drawable.calendario_diciembre, calendario.getId());
            realm.copyToRealm(calendario6);
            Signo calendario7 = new Signo("domingo", R.drawable.calendario_domingo, calendario.getId());
            realm.copyToRealm(calendario7);
            Signo calendario8 = new Signo("en-punto", R.drawable.calendario_en_punto, calendario.getId());
            realm.copyToRealm(calendario8);
            Signo calendario9 = new Signo("estaciones", R.drawable.calendario_estaciones, calendario.getId());
            realm.copyToRealm(calendario9);
            Signo calendario10 = new Signo("fiesta", R.drawable.calendario_fiesta, calendario.getId());
            realm.copyToRealm(calendario10);
            Signo calendario11 = new Signo("fin-de-semana", R.drawable.calendario_fin_de_semana, calendario.getId());
            realm.copyToRealm(calendario11);
            Signo calendario12 = new Signo("hora-interrogativa", R.drawable.calendario_hora_interrogativa, calendario.getId());
            realm.copyToRealm(calendario12);
            Signo calendario13 = new Signo("hoy", R.drawable.calendario_hoy, calendario.getId());
            realm.copyToRealm(calendario13);
            Signo calendario14 = new Signo("invierno", R.drawable.calendario_invierno, calendario.getId());
            realm.copyToRealm(calendario14);
            Signo calendario15 = new Signo("jueves", R.drawable.calendario_jueves, calendario.getId());
            realm.copyToRealm(calendario15);
            Signo calendario16 = new Signo("junio", R.drawable.calendario_junio, calendario.getId());
            realm.copyToRealm(calendario16);
            Signo calendario17 = new Signo("la-hora-de", R.drawable.calendario_la_hora_de, calendario.getId());
            realm.copyToRealm(calendario17);
            Signo calendario18 = new Signo("lunes", R.drawable.calendario_lunes, calendario.getId());
            realm.copyToRealm(calendario18);
            Signo calendario19 = new Signo("manana", R.drawable.calendario_manana, calendario.getId());
            realm.copyToRealm(calendario19);
            Signo calendario20 = new Signo("martes", R.drawable.calendario_martes, calendario.getId());
            realm.copyToRealm(calendario20);
            Signo calendario21 = new Signo("mayo", R.drawable.calendario_mayo, calendario.getId());
            realm.copyToRealm(calendario21);
            Signo calendario22 = new Signo("menos-cuarto", R.drawable.calendario_menos_cuarto, calendario.getId());
            realm.copyToRealm(calendario22);
            Signo calendario23 = new Signo("mes", R.drawable.calendario_mes, calendario.getId());
            realm.copyToRealm(calendario23);
            Signo calendario24 = new Signo("meses-del-ano", R.drawable.calendario_meses_del_ano, calendario.getId());
            realm.copyToRealm(calendario24);
            Signo calendario25 = new Signo("miercoles", R.drawable.calendario_miercoles, calendario.getId());
            realm.copyToRealm(calendario25);
            Signo calendario26 = new Signo("navidad", R.drawable.calendario_navidad, calendario.getId());
            realm.copyToRealm(calendario26);
            Signo calendario27 = new Signo("noviembre", R.drawable.calendario_noviembre, calendario.getId());
            realm.copyToRealm(calendario27);
            Signo calendario28 = new Signo("octubre", R.drawable.calendario_octubre, calendario.getId());
            realm.copyToRealm(calendario28);
            Signo calendario29 = new Signo("otono", R.drawable.calendario_otono, calendario.getId());
            realm.copyToRealm(calendario29);
            Signo calendario30 = new Signo("papa-noel", R.drawable.calendario_papa_noel, calendario.getId());
            realm.copyToRealm(calendario30);
            Signo calendario31 = new Signo("por-la-manana", R.drawable.calendario_por_la_manana, calendario.getId());
            realm.copyToRealm(calendario31);
            Signo calendario32 = new Signo("por-la-noche", R.drawable.calendario_por_la_noche, calendario.getId());
            realm.copyToRealm(calendario32);
            Signo calendario33 = new Signo("por-la-tarde", R.drawable.calendario_por_la_tarde, calendario.getId());
            realm.copyToRealm(calendario33);
            Signo calendario34 = new Signo("primavera", R.drawable.calendario_primavera, calendario.getId());
            realm.copyToRealm(calendario34);
            Signo calendario35 = new Signo("reyes-magos", R.drawable.calendario_reyes_magos, calendario.getId());
            realm.copyToRealm(calendario35);
            Signo calendario36 = new Signo("sabado", R.drawable.calendario_sabado, calendario.getId());
            realm.copyToRealm(calendario36);
            Signo calendario37 = new Signo("semana", R.drawable.calendario_semana, calendario.getId());
            realm.copyToRealm(calendario37);
            Signo calendario38 = new Signo("septiembre", R.drawable.calendario_septiembre, calendario.getId());
            realm.copyToRealm(calendario38);
            Signo calendario39 = new Signo("tiempo", R.drawable.calendario_tiempo, calendario.getId());
            realm.copyToRealm(calendario39);
            Signo calendario40 = new Signo("verano", R.drawable.calendario_verano, calendario.getId());
            realm.copyToRealm(calendario40);
            Signo calendario41 = new Signo("viernes", R.drawable.calendario_viernes, calendario.getId());
            realm.copyToRealm(calendario41);
            Signo calendario42 = new Signo("y-cuarto", R.drawable.calendario_y_cuarto, calendario.getId());
            realm.copyToRealm(calendario42);
            Signo calendario43 = new Signo("y-media", R.drawable.calendario_y_media, calendario.getId());
            realm.copyToRealm(calendario43);

            Signo casa1 = new Signo("alfombra", R.drawable.casa_alfombra, casa.getId());
            realm.copyToRealm(casa1);
            Signo casa2 = new Signo("armario", R.drawable.casa_armario, casa.getId());
            realm.copyToRealm(casa2);
            Signo casa3 = new Signo("banera", R.drawable.casa_banera, casa.getId());
            realm.copyToRealm(casa3);
            Signo casa4 = new Signo("bano", R.drawable.casa_bano, casa.getId());
            realm.copyToRealm(casa4);
            Signo casa5 = new Signo("cacerola", R.drawable.casa_cacerola, casa.getId());
            realm.copyToRealm(casa5);
            Signo casa6 = new Signo("cama", R.drawable.casa_cama, casa.getId());
            realm.copyToRealm(casa6);
            Signo casa7 = new Signo("casa", R.drawable.casa_casa, casa.getId());
            realm.copyToRealm(casa7);
            Signo casa8 = new Signo("cepillo", R.drawable.casa_cepillo, casa.getId());
            realm.copyToRealm(casa8);
            Signo casa9 = new Signo("champu", R.drawable.casa_champu, casa.getId());
            realm.copyToRealm(casa9);
            Signo casa10 = new Signo("cocina", R.drawable.casa_cocina, casa.getId());
            realm.copyToRealm(casa10);
            Signo casa11 = new Signo("colonia", R.drawable.casa_colonia, casa.getId());
            realm.copyToRealm(casa11);
            Signo casa12 = new Signo("cristal", R.drawable.casa_cristal, casa.getId());
            realm.copyToRealm(casa12);
            Signo casa13 = new Signo("cuchara", R.drawable.casa_cuchara, casa.getId());
            realm.copyToRealm(casa13);
            Signo casa14 = new Signo("cuchillo", R.drawable.casa_cuchillo, casa.getId());
            realm.copyToRealm(casa14);
            Signo casa15 = new Signo("despertador", R.drawable.casa_despertador, casa.getId());
            realm.copyToRealm(casa15);
            Signo casa16 = new Signo("dormitorio", R.drawable.casa_dormitorio, casa.getId());
            realm.copyToRealm(casa16);
            Signo casa17 = new Signo("espejo", R.drawable.casa_espejo, casa.getId());
            realm.copyToRealm(casa17);
            Signo casa18 = new Signo("esponja", R.drawable.casa_esponja, casa.getId());
            realm.copyToRealm(casa18);
            Signo casa19 = new Signo("fax", R.drawable.casa_fax, casa.getId());
            realm.copyToRealm(casa19);
            Signo casa20 = new Signo("jabon", R.drawable.casa_jabon, casa.getId());
            realm.copyToRealm(casa20);
            Signo casa21 = new Signo("jarra", R.drawable.casa_jarra, casa.getId());
            realm.copyToRealm(casa21);
            Signo casa22 = new Signo("lampara", R.drawable.casa_lampara, casa.getId());
            realm.copyToRealm(casa22);
            Signo casa23 = new Signo("lavabo", R.drawable.casa_lavabo, casa.getId());
            realm.copyToRealm(casa23);
            Signo casa24 = new Signo("lavadora", R.drawable.casa_lavadora, casa.getId());
            realm.copyToRealm(casa24);
            Signo casa25 = new Signo("maceta", R.drawable.casa_maceta, casa.getId());
            realm.copyToRealm(casa25);
            Signo casa26 = new Signo("manta", R.drawable.casa_manta, casa.getId());
            realm.copyToRealm(casa26);
            Signo casa27 = new Signo("maquina", R.drawable.casa_maquina, casa.getId());
            realm.copyToRealm(casa27);
            Signo casa28 = new Signo("mesilla", R.drawable.casa_mesilla, casa.getId());
            realm.copyToRealm(casa28);
            Signo casa29 = new Signo("mueble", R.drawable.casa_mueble, casa.getId());
            realm.copyToRealm(casa29);
            Signo casa30 = new Signo("muneco", R.drawable.casa_muneco, casa.getId());
            realm.copyToRealm(casa30);
            Signo casa31 = new Signo("nevera", R.drawable.casa_nevera, casa.getId());
            realm.copyToRealm(casa31);
            Signo casa32 = new Signo("objeto", R.drawable.casa_objeto, casa.getId());
            realm.copyToRealm(casa32);
            Signo casa33 = new Signo("objetos", R.drawable.casa_objetos, casa.getId());
            realm.copyToRealm(casa33);
            Signo casa34 = new Signo("ordenador", R.drawable.casa_ordenador, casa.getId());
            realm.copyToRealm(casa34);
            Signo casa35 = new Signo("papel", R.drawable.casa_papel, casa.getId());
            realm.copyToRealm(casa35);
            Signo casa36 = new Signo("pasta-de-dientes", R.drawable.casa_pasta_de_dientes, casa.getId());
            realm.copyToRealm(casa36);
            Signo casa37 = new Signo("peine", R.drawable.casa_peine, casa.getId());
            realm.copyToRealm(casa37);
            Signo casa38 = new Signo("pelota", R.drawable.casa_pelota, casa.getId());
            realm.copyToRealm(casa38);
            Signo casa39 = new Signo("plancha", R.drawable.casa_plancha, casa.getId());
            realm.copyToRealm(casa39);
            Signo casa40 = new Signo("plato", R.drawable.casa_plato, casa.getId());
            realm.copyToRealm(casa40);
            Signo casa41 = new Signo("puerta", R.drawable.casa_puerta, casa.getId());
            realm.copyToRealm(casa41);
            Signo casa42 = new Signo("sabana", R.drawable.casa_sabana, casa.getId());
            realm.copyToRealm(casa42);
            Signo casa43 = new Signo("salon", R.drawable.casa_salon, casa.getId());
            realm.copyToRealm(casa43);
            Signo casa44 = new Signo("sarten", R.drawable.casa_sarten, casa.getId());
            realm.copyToRealm(casa44);
            Signo casa45 = new Signo("servilleta", R.drawable.casa_servilleta, casa.getId());
            realm.copyToRealm(casa45);
            Signo casa46 = new Signo("silla", R.drawable.casa_silla, casa.getId());
            realm.copyToRealm(casa46);
            Signo casa47 = new Signo("sofa", R.drawable.casa_sofa, casa.getId());
            realm.copyToRealm(casa47);
            Signo casa48 = new Signo("telefono", R.drawable.casa_telefono, casa.getId());
            realm.copyToRealm(casa48);
            Signo casa49 = new Signo("televisor", R.drawable.casa_televisor, casa.getId());
            realm.copyToRealm(casa49);
            Signo casa50 = new Signo("tenedor", R.drawable.casa_tenedor, casa.getId());
            realm.copyToRealm(casa50);
            Signo casa51 = new Signo("toalla", R.drawable.casa_toalla, casa.getId());
            realm.copyToRealm(casa51);
            Signo casa52 = new Signo("vaso", R.drawable.casa_vaso, casa.getId());
            realm.copyToRealm(casa52);
            Signo casa53 = new Signo("ventana", R.drawable.casa_ventana, casa.getId());
            realm.copyToRealm(casa53);
            Signo casa54 = new Signo("video", R.drawable.casa_video, casa.getId());
            realm.copyToRealm(casa54);
            realm.commitTransaction();
            return new AtomicInteger(0);
        }
    }
}
